figure_manifest <- data.frame(
  artifact = character(),
  source_type = character(),
  source_detail = character(),
  stringsAsFactors = FALSE
)
assign("figure_manifest", figure_manifest, envir = globalenv())

add_figure_source <- function(artifact, source_type, source_detail) {
  invisible(NULL)
}

build_figure <- function(artifact, expr) {
  unlink(artifact_output_file(artifact))
  tryCatch(
    force(expr),
    error = function(err) {
      record_artifact(artifact, FALSE, "generation_failed", conditionMessage(err))
      record_issue("04_make_manuscript_figures", "generation failed", paste(artifact, conditionMessage(err)))
    }
  )
}

make_model_panel_figure <- function(artifact, plots, labels, ncol, width, height, source_detail) {
  write_ggplot_panel_figure(
    artifact_output_file(artifact),
    plots = plots,
    labels = labels,
    ncol = ncol,
    width = width,
    height = height
  )
  record_artifact(
    artifact,
    TRUE,
    "generated_from_model_outputs",
    "Generated by the R single-omics workflow from local model-output RDS files under ignored data/model_outputs/single_omics."
  )
  add_figure_source(artifact, "model_output_rds", source_detail)
}

mark_cross_omics_present <- function(artifact) {
  # These figures come from code/cross_omics/02_make_figures.R, which is run
  # separately. The PDFs stay in results/figures so the submission set is
  # complete; deleting them here would drop them from the manuscript copy.
  present <- file.exists(artifact_output_file(artifact))
  record_artifact(
    artifact,
    present,
    if (present) "cross_omics_present" else "cross_omics_missing",
    "Generated by code/cross_omics/02_make_figures.R. This step only checks that the file is still present."
  )
  add_figure_source(artifact, "cross_omics_r", "code/cross_omics/02_make_figures.R")
}

model_outputs <- load_prediction_model_outputs(paths)

build_figure("Fig1_flowchart.pdf", {
  # Verify every drawn count against the data before drawing, and stop on a
  # mismatch rather than publishing a stale number. This mirrors compare_table1()
  # in 03_; Figure 1 carried a superseded genus count for exactly as long as this
  # check existed but went uncalled.
  flow <- participant_flow_counts(model_outputs)
  drift <- flow[flow$recomputed != flow$in_figure, , drop = FALSE]
  if (nrow(drift)) {
    stop("Figure 1 counts disagree with the data: ",
         paste(sprintf("%s drawn %d, recomputed %d",
                       drift$quantity, drift$in_figure, drift$recomputed),
               collapse = "; "))
  }
  write_flowchart_pdf(artifact_output_file("Fig1_flowchart.pdf"))
  record_artifact("Fig1_flowchart.pdf", TRUE, "generated", "Generated from code/single_omics/04_make_manuscript_figures.R.")
  add_figure_source("Fig1_flowchart.pdf", "current_r_code", "write_flowchart_pdf")
})

build_figure("Fig2_roc.pdf", {
  write_figure2_pdf(model_outputs, artifact_output_file("Fig2_roc.pdf"))
  record_artifact(
    "Fig2_roc.pdf",
    TRUE,
    "generated_from_model_outputs",
    "Generated from saved p_roc_124 and p_roc_135 objects plus the LR age-only baseline."
  )
})

build_figure("Fig3_bubble_omics.pdf", {
  write_bubble_figure(
    model_outputs,
    artifact_output_file("Fig3_bubble_omics.pdf"),
    figure = "fig3"
  )
  record_artifact(
    "Fig3_bubble_omics.pdf",
    TRUE,
    "generated_from_model_outputs",
    "Generated from top-20 EN and XGB overlap features in saved model-output objects."
  )
})

build_figure("Fig4_bubble_ensamble.pdf", {
  write_bubble_figure(
    model_outputs,
    artifact_output_file("Fig4_bubble_ensamble.pdf"),
    figure = "fig4"
  )
  record_artifact(
    "Fig4_bubble_ensamble.pdf",
    TRUE,
    "generated_from_model_outputs",
    "Generated from top-20 RF+EN and RF+XGB overlap features in saved model-output objects."
  )
})

build_figure("Supplementary_Fig1_omics_importance.pdf", {
  write_supplementary_importance_pdf(
    model_outputs,
    artifact_output_file("Supplementary_Fig1_omics_importance.pdf"),
    figure = "supp1"
  )
  record_artifact(
    "Supplementary_Fig1_omics_importance.pdf",
    TRUE,
    "generated_from_model_outputs",
    "Generated by arranging saved p_en_coef and p_shap3_bee model-output plots."
  )
})

build_figure("Supplementary_Fig2_ensamble_importance.pdf", {
  write_supplementary_importance_pdf(
    model_outputs,
    artifact_output_file("Supplementary_Fig2_ensamble_importance.pdf"),
    figure = "supp2"
  )
  record_artifact(
    "Supplementary_Fig2_ensamble_importance.pdf",
    TRUE,
    "generated_from_model_outputs",
    "Generated by arranging saved p_shap4_bee and p_shap5_bee model-output plots."
  )
})

mark_cross_omics_present("Fig5_micro-metab_correlation.pdf.pdf")
mark_cross_omics_present("Supplementary_Fig3_micro_prot.pdf")
mark_cross_omics_present("Supplementary_Fig4_meta_prot.pdf")
